/**
 * Recommendation Engine Service
 *
 * Generates clinical recommendations based on patient data and clinical rules.
 * Centralizes the logic for creating care plan recommendations.
 */

import { v4 as uuidv4 } from 'uuid';
import {
  ConditionRule,
  ScreeningRule,
  findMatchingConditionRule,
  getApplicableScreeningRules,
} from '../config/clinical-rules';
import { SOURCE_LABELS } from '../constants';
import { getConfig } from '../config';

/**
 * Care plan recommendation generated by the engine
 */
export interface CarePlanRecommendation {
  id: string;
  title: string;
  description: string;
  priority: 'critical' | 'warning' | 'info';
  conditionCode?: string;
  conditionDisplay?: string;
  rationale?: string;
  actions?: Array<{
    description: string;
    type: 'order' | 'referral' | 'education' | 'monitoring';
  }>;
  source?: {
    label: string;
    url?: string;
  };
}

/**
 * FHIR Condition interface (minimal for recommendation engine)
 */
interface FHIRCondition {
  resourceType: 'Condition';
  id?: string;
  clinicalStatus?: {
    coding?: Array<{
      system?: string;
      code?: string;
    }>;
  };
  code?: {
    coding?: Array<{
      system?: string;
      code?: string;
      display?: string;
    }>;
    text?: string;
  };
}

/**
 * FHIR Patient interface (minimal for recommendation engine)
 */
interface FHIRPatient {
  resourceType: 'Patient';
  id?: string;
  birthDate?: string;
  gender?: string;
}

/**
 * FHIR Observation interface (minimal for recommendation engine)
 */
interface FHIRObservation {
  resourceType: 'Observation';
  id?: string;
  code?: {
    coding?: Array<{
      system?: string;
      code?: string;
      display?: string;
    }>;
    text?: string;
  };
  valueQuantity?: {
    value?: number;
    unit?: string;
  };
  effectiveDateTime?: string;
}

/**
 * Generate a recommendation from a condition rule
 */
function createRecommendationFromRule(
  rule: ConditionRule,
  conditionDisplay: string,
  conditionCode?: string
): CarePlanRecommendation {
  // Replace template variables
  const title = rule.titleTemplate.replace('{{conditionDisplay}}', conditionDisplay);
  const description = rule.descriptionTemplate.replace('{{conditionDisplay}}', conditionDisplay);

  return {
    id: uuidv4(),
    title,
    description,
    priority: rule.priority,
    conditionCode,
    conditionDisplay,
    rationale: rule.rationale,
    actions: rule.actions,
    source: rule.source,
  };
}

/**
 * Generate a recommendation from a screening rule
 */
function createRecommendationFromScreeningRule(
  rule: ScreeningRule
): CarePlanRecommendation {
  return {
    id: uuidv4(),
    title: rule.title,
    description: rule.description,
    priority: rule.priority,
    rationale: rule.rationale,
    source: rule.source,
  };
}

/**
 * Check if a condition is active
 */
function isActiveCondition(condition: FHIRCondition): boolean {
  const clinicalStatus = condition.clinicalStatus?.coding?.[0]?.code;

  // If no status, assume active
  if (!clinicalStatus) {
    return true;
  }

  return clinicalStatus === 'active';
}

/**
 * Calculate patient age from birth date
 */
function calculateAge(birthDate: string): number {
  const birth = new Date(birthDate);
  const today = new Date();

  return Math.floor(
    (today.getTime() - birth.getTime()) / (365.25 * 24 * 60 * 60 * 1000)
  );
}

/**
 * Generate condition-based recommendations
 */
export function generateConditionRecommendations(
  conditions: FHIRCondition[]
): CarePlanRecommendation[] {
  const recommendations: CarePlanRecommendation[] = [];

  for (const condition of conditions) {
    // Skip inactive conditions
    if (!isActiveCondition(condition)) {
      continue;
    }

    const coding = condition.code?.coding?.[0];
    if (!coding?.code || !coding?.system) {
      continue;
    }

    const conditionDisplay =
      coding.display || condition.code?.text || 'Unknown condition';

    // Find matching rule
    const rule = findMatchingConditionRule(coding.code, coding.system);
    if (rule) {
      recommendations.push(
        createRecommendationFromRule(rule, conditionDisplay, coding.code)
      );
    }
  }

  return recommendations;
}

/**
 * Generate screening recommendations based on patient demographics
 */
export function generateScreeningRecommendations(
  patient: FHIRPatient | undefined
): CarePlanRecommendation[] {
  if (!patient?.birthDate) {
    return [];
  }

  const age = calculateAge(patient.birthDate);
  const applicableRules = getApplicableScreeningRules(age, patient.gender);

  return applicableRules.map((rule) =>
    createRecommendationFromScreeningRule(rule)
  );
}

/**
 * Generate vital sign recommendations
 */
export function generateVitalSignRecommendations(
  observations: FHIRObservation[]
): CarePlanRecommendation[] {
  const recommendations: CarePlanRecommendation[] = [];
  const config = getConfig();

  if (observations.length === 0) {
    recommendations.push({
      id: uuidv4(),
      title: 'Missing Recent Vital Signs',
      description:
        'No recent vital signs on record. Consider capturing vital signs for this patient.',
      priority: 'info',
      source: {
        label: SOURCE_LABELS.PRISM_CARE_PLAN,
        url: config.mlServiceUrl,
      },
    });
  }

  return recommendations;
}

/**
 * Generate all care plan recommendations for a patient
 */
export async function generateAllRecommendations(
  patient: FHIRPatient | undefined,
  conditions: FHIRCondition[],
  observations: FHIRObservation[]
): Promise<CarePlanRecommendation[]> {
  const recommendations: CarePlanRecommendation[] = [];

  // Condition-based recommendations
  recommendations.push(...generateConditionRecommendations(conditions));

  // Vital sign recommendations
  recommendations.push(...generateVitalSignRecommendations(observations));

  // Screening recommendations (based on patient demographics)
  recommendations.push(...generateScreeningRecommendations(patient));

  return recommendations;
}
